from __future__ import annotations

from typing import Any, Dict, List


def _mcq(question: str, options: List[str], answer_index: int, explanation: str) -> Dict[str, Any]:
    return {"question": question, "options": options, "answer_index": answer_index, "explanation": explanation}


def _mission(question_id: str, qtype: str, question: str, expected_focus: List[str]) -> Dict[str, Any]:
    return {"question_id": question_id, "type": qtype, "question": question, "expected_focus": expected_focus}


ML_ARCHITECT_COMPLETION_BLUEPRINTS: Dict[str, Dict[str, Any]] = {
    "mlf_021": {
        "topic_id": "mlf_021",
        "title": "Validation under time, group, and leakage constraints",
        "module": "ML Architect Completion Block",
        "definition": "Validation strategy is the design of an honest rehearsal for the production decision, using splits that preserve the independence and ordering constraints of the real problem.",
        "plain_intuition": "A random split is not automatically fair. If production predicts future months, unseen vehicles, or new plants, validation must imitate that boundary.",
        "why_it_exists": "An apparently strong model can be approved using a split that lets similar entities or future information leak across train and validation sets.",
        "core_mechanism": "Choose the split unit from the production boundary: time-based split for future prediction, group split for unseen assets or customers, stratification for class balance only when row-level independence is valid, and nested validation when tuning must remain separate from final testing.",
        "worked_example": "A predictive-quality dataset contains repeated measurements from each machine. A random row split puts readings from Machine A into both train and validation. The model appears strong because it has effectively already seen that machine. Group holdout by machine gives a more honest estimate for performance on a newly installed machine.",
        "nuances": [
            "Stratification preserves class ratios, but does not solve time leakage or entity leakage.",
            "Cross-validation estimates variability only when its folds match deployment reality.",
            "The test set must remain untouched while design and tuning decisions are being made.",
        ],
        "when_matters": "It matters when data has time order, repeated assets, multiple plants, suppliers, patients, customers, batches, or tuning decisions.",
        "when_less": "It matters less only when observations are genuinely independent and the deployment population is stationary.",
        "common_confusions": [
            "Using k-fold cross-validation by default without checking temporal or group leakage.",
            "Calling a validation scheme robust merely because it reports an average score.",
            "Tuning on the final test set and then still calling it unbiased evidence.",
        ],
        "architect_implications": [
            "Declare the production generalization boundary before selecting the split.",
            "Store split policy, group/time columns, exclusion rules, and fold-level metrics as approval evidence.",
        ],
        "system_design_controls": ["split policy record", "group leakage test", "temporal cutoff validation", "untouched final test set", "fold-level segment report"],
        "mission_answer_frame": [
            "State the future production boundary.",
            "Choose the split that imitates that boundary.",
            "Name the leakage a wrong split would create.",
            "Specify evidence to store and review.",
            "State the approval decision.",
        ],
        "do_not_waste_words": ["Do not say use cross-validation generically.", "Do not treat stratification as leakage prevention.", "Do not optimize on the final test set."],
        "mcqs": [
            _mcq("You must predict failures for future months. Which split is most honest?", ["Time-ordered validation with future periods held out.", "Random row split only.", "Fit on all data then report training score.", "Shuffle labels before splitting."], 0, "Future prediction requires a temporal holdout."),
            _mcq("Several rows belong to the same vehicle, and deployment covers unseen vehicles. What is the key control?", ["Keep each vehicle wholly in one split using group holdout.", "Use larger font in the report.", "Always oversample vehicles.", "Remove the target label."], 0, "Group isolation prevents entity memorization from inflating validation."),
            _mcq("What does stratification solve?", ["Class-ratio preservation across splits.", "Future leakage.", "Repeated-asset leakage.", "Test-set overuse."], 0, "Stratification does not protect time or group boundaries."),
            _mcq("What is the purpose of an untouched final test set?", ["Provide final unbiased evidence after model and tuning decisions.", "Provide data to tune every hyperparameter.", "Replace monitoring.", "Guarantee causality."], 0, "A test set loses its role once repeatedly used for selection."),
        ],
        "missions": [
            _mission("q1", "concept_check", "Explain why cross-validation is not automatically a valid validation strategy for manufacturing ML.", ["deployment boundary", "time or group leakage", "honest validation"]),
            _mission("q2", "tiny_hands_on", "You have 24 months of sensor data from 12 production lines and must predict next-month defects on existing and new lines. Design the validation split you would test first.", ["time cutoff", "line grouping", "comparison of deployment scenarios"]),
            _mission("q3", "failure_diagnosis", "A model scored very highly in random cross-validation, then failed on a newly commissioned line. What likely went wrong and what evidence would prove it?", ["group leakage", "fold composition", "new-line holdout"]),
            _mission("q4", "architect_decision", "Define a validation-governance standard for a predictive-quality platform supporting multiple plants and retraining cycles.", ["split policy", "test-set isolation", "approval evidence", "owner"]),
            _mission("q5", "teachback", "Explain to a project sponsor why a lower score from an honest split is more useful than a higher score from an unrealistic split.", ["simple explanation", "trustworthy estimate", "deployment risk"]),
        ],
    },
    "mlf_022": {
        "topic_id": "mlf_022",
        "title": "Hyperparameter tuning without fooling yourself",
        "module": "ML Architect Completion Block",
        "definition": "Hyperparameter tuning is controlled experimentation over model settings, where selection must be separated from final evidence to avoid overfitting the validation process.",
        "plain_intuition": "Trying hundreds of settings is a form of learning. You can overfit your validation set even when you never touch the training labels incorrectly.",
        "why_it_exists": "Teams often report the best validation score after repeated searching, without acknowledging that the score has become part of the optimization loop.",
        "core_mechanism": "Define a tuning budget and search space, tune only inside the development validation process, record all trials, select a candidate, then evaluate once on an untouched final test set.",
        "worked_example": "A team tests 150 model settings and advertises the best validation F1. The chosen score may include luck specific to that validation window. A disciplined approach records the search, selects using inner validation, and uses a locked later-period test set for approval.",
        "nuances": [
            "Random search often explores a limited budget more efficiently than exhaustive grids.",
            "Nested validation is useful when data is limited and model comparison needs unbiased estimation.",
            "Tuning threshold and tuning model parameters are both decision searches and need separation from final test evidence.",
        ],
        "when_matters": "It matters whenever multiple models, feature sets, thresholds, or hyperparameters are compared before approval.",
        "when_less": "It matters less for an explicitly fixed baseline used only as a comparison anchor.",
        "common_confusions": ["Calling test-set selection validation.", "Reporting only the winning trial.", "Expanding the search space until the metric becomes attractive."],
        "architect_implications": ["Architects define tuning budget, evaluation hierarchy, experiment log, and approval gate.", "Model selection evidence must show stability and operational trade-offs, not only the maximum score."],
        "system_design_controls": ["tuning budget", "experiment registry", "inner validation", "locked final test set", "candidate approval report"],
        "mission_answer_frame": ["Define what is being tuned.", "Protect final evidence.", "State trial logging and budget.", "Compare winner stability and constraints.", "Approve only after locked-test review."],
        "do_not_waste_words": ["Do not say tune until performance improves.", "Do not promote one winning score without the trial context.", "Do not use the final test set as a search loop."],
        "mcqs": [
            _mcq("A team selects the best of 200 configurations using the test set. What happened?", ["The test set became part of tuning and no longer gives unbiased final evidence.", "The model became causal.", "Monitoring is no longer needed.", "The dataset is automatically balanced."], 0, "Repeated test-based selection invalidates final evidence."),
            _mcq("Why define a tuning budget?", ["To control search-driven overfitting, cost, and reproducibility.", "To guarantee perfect performance.", "To avoid collecting labels.", "To replace validation."], 0, "A bounded, recorded search is auditable."),
            _mcq("What is nested validation useful for?", ["Estimating selection performance while tuning occurs inside inner folds.", "Drawing chart labels.", "Storing passwords.", "Proving causality."], 0, "Nested validation separates tuning from estimation."),
            _mcq("Which output is strongest for review?", ["All trials, selection criterion, locked-test result, and operational constraints.", "Only the single best validation number.", "Only algorithm name.", "Only training time."], 0, "Review requires evidence of the full decision."),
        ],
        "missions": [
            _mission("q1", "concept_check", "Explain how hyperparameter tuning can overfit validation evidence even when training code is technically correct.", ["selection overfitting", "locked test", "search discipline"]),
            _mission("q2", "tiny_hands_on", "You can evaluate 30 model configurations before a quality-model deadline. Design a tuning and final-test process.", ["budget", "search space", "one final evaluation"]),
            _mission("q3", "failure_diagnosis", "A tuned model's validation score is excellent but the final later-period test score collapses. Diagnose likely process failures.", ["validation overuse", "time shift", "trial evidence"]),
            _mission("q4", "architect_decision", "Define governance for model and threshold tuning in a production ML team.", ["experiment registry", "approval gate", "owner", "locked evidence"]),
            _mission("q5", "teachback", "Explain why 'we tried more options and got a higher score' is not automatically good news.", ["simple analogy", "chance", "honest confirmation"]),
        ],
    },
    "mlf_023": {
        "topic_id": "mlf_023",
        "title": "ROC, PR curves, and operating points",
        "module": "ML Architect Completion Block",
        "definition": "ROC and precision-recall curves show how classification behavior changes across thresholds; an operating point is the threshold chosen for actual business action.",
        "plain_intuition": "The model produces risk scores. The business experiences alerts and misses. Curves show the menu of trade-offs; the chosen threshold is the order you place.",
        "why_it_exists": "Single precision or recall values hide whether another threshold could make the model usable or whether rare-event performance is fundamentally weak.",
        "core_mechanism": "Evaluate scores across thresholds, inspect recall against false-positive burden and precision, prefer PR evidence for rare positives, then choose a threshold tied to capacity and cost.",
        "worked_example": "In rare defect detection, ROC-AUC can look strong because true negatives dominate. A PR curve may show that reaching 85% defect recall reduces precision to 18%, creating more inspection alerts than the plant can process.",
        "nuances": ["ROC compares true-positive rate to false-positive rate.", "PR focuses directly on positive detection and alert correctness.", "AUC ranks models; it does not set a deployable threshold."],
        "when_matters": "It matters in alerting, defect detection, warranty escalation, fraud, safety, and other threshold-based operations.",
        "when_less": "It matters less for decisions that do not convert scores into an operational classification or queue.",
        "common_confusions": ["Treating ROC-AUC as threshold policy.", "Ignoring alert capacity.", "Assuming PR-AUC and ROC-AUC answer the same question on rare events."],
        "architect_implications": ["Approval requires a chosen operating point with cost and capacity evidence.", "Monitor threshold performance after deployment because prevalence and workload can change."],
        "system_design_controls": ["threshold evaluation table", "PR curve report", "alert-volume constraint", "threshold owner", "post-deployment precision/recall monitor"],
        "mission_answer_frame": ["State event rarity and cost.", "Use curve appropriate to the risk.", "Select threshold with recall and workload evidence.", "Record owner and fallback.", "Monitor after release."],
        "do_not_waste_words": ["Do not name AUC without an operating decision.", "Do not optimize recall without reviewing false alarms.", "Do not default to 0.5."],
        "mcqs": [
            _mcq("For rare defect detection, which curve usually exposes positive-class usefulness more directly?", ["Precision-recall curve.", "Only a training-loss curve.", "A CPU-utilization chart.", "A random color map."], 0, "PR directly shows recall versus correctness of positive alerts."),
            _mcq("What does a threshold change do?", ["Moves the operating point and changes false positives and false negatives.", "Retrains labels automatically.", "Proves causality.", "Removes drift."], 0, "Thresholds translate scores into decisions."),
            _mcq("What is missing if ROC-AUC is reported without a threshold policy?", ["Operational trade-off and workload decision.", "The model name.", "A larger test set by definition.", "Database schema."], 0, "AUC alone does not set actions."),
            _mcq("High recall with extremely low precision may mean what operational issue?", ["The alert queue can be overwhelmed by false positives.", "All defects were eliminated.", "The split is always valid.", "No monitoring is needed."], 0, "Precision maps directly to alert burden."),
        ],
        "missions": [
            _mission("q1", "concept_check", "Explain why threshold curves and operating points matter beyond reporting precision and recall once.", ["scores to actions", "trade-off", "operating point"]),
            _mission("q2", "tiny_hands_on", "A rare-defect model can achieve 90% recall at 12% precision or 72% recall at 45% precision. Inspection can review 150 alerts per day. What evidence is needed before selecting an operating point?", ["alert volume", "defect cost", "capacity"]),
            _mission("q3", "failure_diagnosis", "A team approved a model using strong ROC-AUC, but the plant stopped using alerts because most were false alarms. What was missed?", ["PR evidence", "threshold selection", "operational adoption"]),
            _mission("q4", "architect_decision", "Design threshold-selection governance for a defect-risk scoring service.", ["PR table", "capacity", "owner", "monitoring"]),
            _mission("q5", "teachback", "Explain ROC/PR curves and a chosen threshold to a quality manager without using unnecessary mathematics.", ["simple explanation", "missed defects", "false alarms"]),
        ],
    },
    "mlf_024": {
        "topic_id": "mlf_024",
        "title": "Probability calibration and confidence",
        "module": "ML Architect Completion Block",
        "definition": "Calibration measures whether predicted probabilities match observed outcome frequencies; a score of 0.8 is reliable only if roughly 80% of similarly scored cases truly occur.",
        "plain_intuition": "Ranking says who looks riskier. Calibration says whether the number printed beside the risk can be trusted as a probability.",
        "why_it_exists": "Risk scores are often fed into intervention budgets, escalation rules, or safety decisions where false confidence is expensive.",
        "core_mechanism": "Group predictions by probability bands, compare predicted versus observed event rates, measure calibration error or Brier score, recalibrate when needed, and set controls for shifts after deployment.",
        "worked_example": "A warranty-risk model labels 100 vehicles around 0.80 risk, but only 35 later become high-risk cases. Its ranking may still be useful, but the 80% probability claim is misleading and can waste intervention budget.",
        "nuances": ["A model may rank well but be poorly calibrated.", "Calibration depends on the deployment population and can drift.", "Recalibration needs held-out evidence and does not repair missing predictors or label problems."],
        "when_matters": "It matters when scores determine triage priority, reserve estimates, escalation intensity, or risk communication.",
        "when_less": "It matters less when only a rough ranking is used and no probability claim or cost allocation follows.",
        "common_confusions": ["Calling raw model scores confidence without checking calibration.", "Assuming good AUC proves good probability accuracy.", "Recalibrating on contaminated or outdated outcomes."],
        "architect_implications": ["Specify whether the product promises ranking or probability.", "Persist calibration evidence, monitoring bands, and recalibration triggers."],
        "system_design_controls": ["reliability diagram", "Brier score", "calibration holdout", "probability-band monitor", "recalibration approval"],
        "mission_answer_frame": ["State ranking versus probability.", "Inspect predicted and observed rate.", "Quantify the gap.", "Define intervention risk.", "Add calibration monitoring and owner."],
        "do_not_waste_words": ["Do not call every score a probability.", "Do not use AUC as calibration proof.", "Do not recalibrate without clean outcome labels."],
        "mcqs": [
            _mcq("A model assigns ~0.8 risk to many cases, but only 0.35 occur. What is the issue?", ["Poor calibration.", "Perfect confidence.", "Data is necessarily leaked.", "The API is down."], 0, "Observed rates do not match stated probabilities."),
            _mcq("Can a model rank cases well but be poorly calibrated?", ["Yes.", "No, never.", "Only if it uses SQL.", "Only if there are no labels."], 0, "Ranking and probability accuracy are different properties."),
            _mcq("What measure can assess probability accuracy?", ["Brier score.", "File name length.", "Only uptime.", "Number of tabs."], 0, "Brier score measures squared probability error."),
            _mcq("What should follow calibration drift?", ["Review/recalibration using clean recent outcomes and controlled release.", "Automatically trust the old probabilities.", "Delete all monitoring.", "Only increase model complexity."], 0, "Probability promises need governed recalibration."),
        ],
        "missions": [
            _mission("q1", "concept_check", "Explain calibration and why a high-risk score is not automatically a reliable probability.", ["predicted vs observed", "ranking distinction", "decision risk"]),
            _mission("q2", "tiny_hands_on", "Among 200 parts scored near 0.75 defect risk, 80 are actually defective. Interpret the calibration gap and next check.", ["observed rate 0.40", "overconfidence", "calibration evidence"]),
            _mission("q3", "failure_diagnosis", "A risk-scoring system over-allocates inspections because reported probabilities are inflated after a supplier shift. What failed?", ["calibration drift", "population shift", "monitoring"]),
            _mission("q4", "architect_decision", "Design a calibration assurance process for an operational risk model.", ["holdout", "bands", "Brier", "owner", "recalibration gate"]),
            _mission("q5", "teachback", "Explain to a business lead the difference between 'highest-risk case' and '80% chance of failure'.", ["simple distinction", "budget impact", "safe claim"]),
        ],
    },
    "mlf_025": {
        "topic_id": "mlf_025",
        "title": "Data quality, label quality, and sampling bias",
        "module": "ML Architect Completion Block",
        "definition": "Data quality governs whether inputs are valid; label quality governs whether the outcome taught to the model is trustworthy; sampling bias governs whether the examples represent the decisions the model will face.",
        "plain_intuition": "An algorithm cannot repair a training story that is wrong, inconsistent, or missing the cases that matter.",
        "why_it_exists": "Real ML systems fail less often from exotic algorithms than from wrong labels, delayed outcomes, proxy targets, missing segments, and changing collection processes.",
        "core_mechanism": "Define data and label contracts, measure missingness and annotation agreement, review proxy-label validity, compare sample coverage to deployment population, and block approval when evidence is weak.",
        "worked_example": "A defect model is trained only on parts sent for manual inspection. Normal production parts and subtle failures are underrepresented, while inspector labels disagree on borderline defects. The model learns inspection-selection bias and unstable targets, not plant-wide defect risk.",
        "nuances": ["More rows do not eliminate systematic bias.", "Delayed labels affect monitoring and retraining timing.", "A proxy label may be convenient but encode business process rather than the true outcome."],
        "when_matters": "It matters in every supervised ML system, especially safety, quality, warranty, fraud, healthcare, and intervention workflows.",
        "when_less": "It matters less only for toy datasets used purely to practise coding, not for decision claims.",
        "common_confusions": ["Treating null cleanup as the whole data-quality problem.", "Calling a proxy outcome ground truth without validation.", "Training on conveniently available samples and assuming production coverage."],
        "architect_implications": ["Architects must define data/label acceptance gates before model approval.", "Coverage and label-drift monitoring should be part of the retraining policy."],
        "system_design_controls": ["data contract checks", "label audit sample", "annotator agreement", "coverage matrix", "proxy-label review", "retraining eligibility gate"],
        "mission_answer_frame": ["State which quality dimension failed.", "Show evidence to measure it.", "Connect it to model behavior.", "Define acceptance gate and owner.", "State corrective action before retraining."],
        "do_not_waste_words": ["Do not blame algorithm first.", "Do not say clean data generically.", "Do not train on biased samples without coverage evidence."],
        "mcqs": [
            _mcq("Two inspectors disagree frequently on defect labels. What is primarily at risk?", ["Label quality and learnable target consistency.", "API uptime.", "Chart formatting.", "Threshold alone."], 0, "Inconsistent labels make the target unreliable."),
            _mcq("Training only on cases previously escalated for inspection creates what risk?", ["Sampling or selection bias.", "Guaranteed generalization.", "Automatic calibration.", "No risk."], 0, "The sample is shaped by prior process decisions."),
            _mcq("A warranty claim is used as a proxy for actual defect. What must be checked?", ["Whether the proxy captures the target without systematic exclusions or delays.", "Only model file size.", "Only dashboard color.", "Nothing because claims are labels."], 0, "Proxy labels need validity review."),
            _mcq("What is strongest before retraining on new labelled data?", ["Quality/coverage checks and label audit before model update.", "Automatic ingestion without review.", "Ignore new categories.", "Delete old evidence."], 0, "Retraining should not amplify poor data."),
        ],
        "missions": [
            _mission("q1", "concept_check", "Explain the difference between input data quality, label quality, and sampling bias, and why each can break ML.", ["three distinctions", "model impact", "evidence"]),
            _mission("q2", "tiny_hands_on", "Two inspectors labelled the same 100 parts and disagreed on 22. In addition, only escalated parts are present in training. What would you investigate before modelling?", ["agreement rate", "selection bias", "label protocol"]),
            _mission("q3", "failure_diagnosis", "A defect model performs poorly for a supplier that was rarely inspected during training. Diagnose the failure chain.", ["coverage gap", "sampling bias", "label availability"]),
            _mission("q4", "architect_decision", "Define data and label acceptance gates for a predictive-quality ML platform.", ["contracts", "audit", "coverage", "owner", "block release"]),
            _mission("q5", "teachback", "Explain why better algorithms cannot rescue unreliable training labels and biased samples.", ["simple explanation", "business risk", "quality gate"]),
        ],
    },
    "checkpoint_ml_architect_001": {
        "topic_id": "checkpoint_ml_architect_001",
        "title": "Checkpoint 2: ML Architect Readiness Review",
        "module": "ML Architect Completion Checkpoint",
        "definition": "The ML Architect checkpoint tests whether validation, tuning, thresholding, calibration, data quality, monitoring, and governance can be joined into one defensible production decision.",
        "plain_intuition": "Knowing the pieces is not enough. You must be able to stop an unsafe model, approve a defensible one, and specify exactly what evidence changes the decision.",
        "why_it_exists": "The learner is about to build a capstone and then move into neural networks; the ML decision discipline must be explicit before complexity increases.",
        "core_mechanism": "Use an end-to-end case: define target and costs, establish honest validation, compare models and operating points, check calibration and data/label quality, then specify monitoring, approval, and fallback.",
        "worked_example": "A quality-risk model ranks defects well, but its test set mixes machine histories, probabilities are overconfident, and one supplier is underrepresented. A strong architect does not deploy it with a dashboard. They repair evidence, select an operating point, and define controls before approval.",
        "nuances": ["Strong ranking cannot compensate for dishonest validation.", "A safe threshold cannot compensate for poor labels.", "Monitoring does not retroactively validate a weak approval decision."],
        "when_matters": "It matters before capstone delivery or any real ML architecture recommendation.",
        "when_less": "It is not a casual revision quiz; it is an approval-readiness gate.",
        "common_confusions": ["Treating controls as a checklist without decision logic.", "Giving a deployment plan without rejection conditions.", "Optimizing the model while ignoring evidence quality."],
        "architect_implications": ["The checkpoint must be passed cleanly before the capstone unlocks.", "Evidence, owners, triggers, and fallback are required for architect-grade approval."],
        "system_design_controls": ["validation evidence pack", "threshold decision record", "calibration report", "data/label audit", "monitoring plan", "approval gate"],
        "mission_answer_frame": ["State decision and why.", "Cite evidence and gaps.", "Define corrective action.", "Name owner and trigger.", "Approve, conditionally approve, or reject."],
        "do_not_waste_words": ["Do not list concepts without a decision.", "Do not approve on average metrics only.", "Do not call dashboards governance."],
        "mcqs": [
            _mcq("A time-based defect model is tuned repeatedly on the final quarter test set. What is invalidated?", ["The final test evidence.", "Only API latency.", "Only chart labels.", "Nothing."], 0, "The test set has entered the selection loop."),
            _mcq("For rare defects, what evidence is essential for operating-point approval?", ["PR trade-off and alert workload alongside defect recall.", "Accuracy alone.", "Model name.", "Training duration only."], 0, "Rare-event operations depend on recall and false-alert burden."),
            _mcq("Predicted 0.8-risk cases fail only 0.35 of the time. What is required?", ["Calibration review before using the score as a probability.", "Automatic deployment.", "Ignore outcomes.", "Only more UI cards."], 0, "Probability claims require calibration."),
            _mcq("If one plant was absent from training, what is the first architectural concern?", ["Coverage and sampling bias for that deployment segment.", "Only threshold font.", "Only CPU scaling.", "No concern."], 0, "Unrepresented segments undermine generalization evidence."),
            _mcq("Rows from the same machine are in train and validation while deployment targets new machines. Which finding is most important?", ["Validation may be inflated by group leakage.", "The model is automatically calibrated.", "The test set is untouched by definition.", "More epochs solve the boundary issue."], 0, "Entity overlap can make validation unrealistic."),
            _mcq("A configuration wins only after 300 unlogged trials. What is missing?", ["Auditable tuning evidence and controlled search budget.", "A different UI layout.", "A guarantee of causality.", "A lower Python version."], 0, "Selection history matters for confidence in reported performance."),
            _mcq("A threshold catches defects but creates more daily alerts than inspectors can process. What should happen?", ["Revisit the operating point or workflow capacity before release.", "Deploy and ignore alert backlog.", "Remove monitoring.", "Report AUC only."], 0, "Operating decisions must fit capacity."),
            _mcq("Two inspectors disagree on 25 percent of sampled labels. What is the immediate modelling risk?", ["The target itself may be inconsistent and needs a label audit.", "Perfect training signal.", "Automatic probability calibration.", "No production impact."], 0, "Inconsistent outcomes limit learnable performance."),
            _mcq("Which release package is architect-grade?", ["Validation policy, threshold note, calibration and label evidence, monitoring/fallback plan, and owners.", "A single accuracy number.", "A screenshot of a notebook.", "A list of algorithms tried."], 0, "Approval depends on evidence and operating controls."),
            _mcq("Performance labels arrive 45 days after predictions. What can still be monitored immediately?", ["Input and prediction distribution shifts with delayed performance review.", "True recall immediately without labels.", "Nothing at all.", "Only model file name."], 0, "Monitoring must handle delayed truth."),
        ],
        "missions": [
            _mission("q1", "concept_check", "Connect honest validation, disciplined tuning, operating-point choice, calibration, and data/label quality into one ML approval argument.", ["integrated reasoning", "decision evidence", "release gate"]),
            _mission("q2", "tiny_hands_on", "A defect-risk model achieves ROC-AUC 0.94, PR-AUC 0.31, and at the proposed threshold recall 0.82 with precision 0.16. What do you review before go-live?", ["rare event", "alert workload", "threshold decision"]),
            _mission("q3", "failure_diagnosis", "A newly deployed model floods inspectors with alerts and overstates risk for a new supplier. Diagnose likely validation, calibration, and data-quality failures.", ["supplier coverage", "calibration", "operating point", "evidence"]),
            _mission("q4", "architect_decision", "Issue an approval decision for a predictive-quality model and define the minimum evidence pack, controls, triggers, and owners.", ["approve/reject condition", "evidence pack", "monitoring", "owner"]),
            _mission("q5", "teachback", "Explain to an operations leader what must be proven before trusting a model-generated risk score.", ["plain language", "probability caution", "safe action"]),
        ],
    },
    "capstone_ml_architect_001": {
        "topic_id": "capstone_ml_architect_001",
        "title": "Capstone: Predictive Quality ML Architecture",
        "module": "ML Architect Capstone",
        "definition": "The capstone is an evidence-backed architecture exercise: design a predictive-quality ML pipeline, defend each decision, and define how the model remains safe after deployment.",
        "plain_intuition": "This is no longer a lesson answer. It is your mini design review. You must show what you would build, what you would measure, what would stop release, and how production would be controlled.",
        "why_it_exists": "Architecture skill appears when concepts become a defensible system decision with artifacts, gates, trade-offs, and operational ownership.",
        "core_mechanism": "Frame the quality problem, profile and validate data, define split and baseline, design feature/encoding pipeline, compare models, choose threshold, analyse errors, constrain explanations, define monitoring/retraining, and produce a final decision record.",
        "worked_example": "You are designing an early-warning model for a tube-forming line. Scrap is rare but expensive. Sensor, material, shift, line, and inspection outcome data are available. The deliverable is not 'highest accuracy'. It is a governed pipeline that catches avoidable scrap early without overwhelming operators or silently degrading.",
        "nuances": ["A capstone answer must state assumptions when real data is not supplied.", "Artifacts can be concise but must be implementable.", "A model may be rejected or restricted even if an experiment score is attractive."],
        "when_matters": "It is the bridge from ML study to architecture practice and portfolio evidence.",
        "when_less": "It is not useful as a memory exercise or as generic ML theory.",
        "common_confusions": ["Writing a project essay without decision artifacts.", "Optimising accuracy instead of operational quality risk.", "Treating monitoring and governance as future work."],
        "architect_implications": ["The output should be usable as an architecture review pack.", "A capstone pass requires implementable controls, a passing Code Lab policy function, and a clear release decision."],
        "system_design_controls": ["architecture decision record", "model card", "threshold decision note", "error analysis table", "monitoring plan", "fallback policy", "retraining approval gate"],
        "mission_answer_frame": ["State scope, target, and business cost.", "Define data, pipeline, and validation.", "Defend metrics, threshold, and model choice.", "Show error/explanation limits.", "Deliver monitoring, fallback, ownership, and approval decision."],
        "do_not_waste_words": ["Do not answer as five disconnected lessons.", "Do not claim automatic process control.", "Do not skip artifacts or release conditions."],
        "mcqs": [
            _mcq("What is the first capstone decision?", ["Define target, prediction timing, and business cost of errors.", "Choose the most complex algorithm.", "Draw a dashboard.", "Pick a 0.5 threshold."], 0, "Architecture begins with the decision and target boundary."),
            _mcq("What makes a baseline useful in the capstone?", ["It proves whether additional complexity improves the decision enough to justify it.", "It eliminates monitoring.", "It guarantees calibration.", "It proves causality."], 0, "Baseline supports justification."),
            _mcq("What is required before an automated intervention based on explanations?", ["Validation and an approval path because explanations are not causal proof.", "Only a SHAP chart.", "Only high accuracy.", "Nothing."], 0, "Process action needs governance."),
            _mcq("Which artifact states why a threshold was chosen?", ["Threshold decision note.", "UI color palette.", "Login file.", "Model filename."], 0, "The operating point must be defended."),
        ],
        "missions": [
            _mission("q1", "concept_check", "Problem framing artifact: define a predictive-quality use case, target event, prediction point, false-negative/false-positive cost, and explicit out-of-scope boundaries.", ["problem framing", "target timing", "cost of errors", "scope"]),
            _mission("q2", "tiny_hands_on", "Validation and model artifact: define dataset checks, split strategy, baseline, candidate pipeline, evaluation metrics, and threshold selection evidence.", ["data profile", "split", "baseline", "metrics", "threshold"]),
            _mission("q3", "failure_diagnosis", "Risk analysis artifact: provide an error-analysis table design, explainability limits, and three release-blocking failure patterns with investigation actions.", ["segments", "errors", "interpretability limits", "release block"]),
            _mission("q4", "architect_decision", "Operations artifact: define monitoring signals, thresholds, fallback action, retraining trigger, validation gate, and accountable owners.", ["monitoring", "fallback", "retraining", "owner"]),
            _mission("q5", "teachback", "Final architect readout: give the deployment recommendation and summarize the model card and architecture decision record you would hand to stakeholders.", ["recommendation", "model card", "ADR", "stakeholder clarity"]),
        ],
    },
}


ML_ARCHITECT_TUTOR_EXPANSIONS: Dict[str, Dict[str, Any]] = {
    "mlf_021": {
        "teacher_walkthrough": "Start from the deployment boundary, not the favourite validation technique. Rows from the same machine can look independent in a spreadsheet while still carrying the same machine identity. Future months cannot help predict past months. Validation is credible only when it mimics the unknowns the model will face.",
        "safe_vs_unsafe": ["Unsafe: random rows across repeated machines and future periods.", "Safe: test time and group holdouts that mirror actual release scenarios."],
        "mini_checks": ["Will production face new time periods, new groups, or both?", "Can the same physical asset appear in both splits?", "Which set remains untouched after tuning?"],
    },
    "mlf_022": {
        "teacher_walkthrough": "A search process can learn the quirks of validation data. Every extra trial is another chance to choose a lucky configuration. The safeguard is not less curiosity; it is separation: bounded tuning evidence versus final approval evidence.",
        "safe_vs_unsafe": ["Unsafe: keep opening the final test result until one design wins.", "Safe: fix the search plan, log trials, and open locked evidence once."],
        "mini_checks": ["What is the tuning budget?", "Which data is locked until selection is complete?", "What trial history would an approver see?"],
    },
    "mlf_023": {
        "teacher_walkthrough": "A risk score is not an alarm until a threshold is applied. Moving that threshold changes the balance between caught defects and wasted inspections. A curve is useful because it makes the cost trade-off visible before operators are forced to live with it.",
        "safe_vs_unsafe": ["Unsafe: celebrate AUC and leave operations with default threshold alerts.", "Safe: select and govern an operating point using recall, precision, volume, and cost."],
        "mini_checks": ["How rare is the positive event?", "How many alerts can operations handle?", "What threshold breach triggers review?"],
    },
    "mlf_024": {
        "teacher_walkthrough": "There are two very different promises: 'this case is riskier than another' and 'this case has an 80 percent probability'. A model can deliver the first while failing the second. Calibration controls the honesty of probability language.",
        "safe_vs_unsafe": ["Unsafe: convert raw scores into confident probability statements.", "Safe: compare predicted bands with observed rates and govern recalibration."],
        "mini_checks": ["Is the product using ranking or stated probability?", "What is the observed rate in each risk band?", "What happens when calibration drifts?"],
    },
    "mlf_025": {
        "teacher_walkthrough": "Your model studies the records you give it, not the reality you wished you recorded. If only escalated parts are labelled, if two inspectors disagree, or if a proxy target is delayed, the model can be technically optimized and operationally wrong.",
        "safe_vs_unsafe": ["Unsafe: improve algorithm complexity on untrusted labels and biased samples.", "Safe: audit labels and coverage, define acceptance gates, then model."],
        "mini_checks": ["Who or what creates the label?", "Which production segments are missing?", "What evidence blocks training or release?"],
    },
    "checkpoint_ml_architect_001": {
        "teacher_walkthrough": "This is the point where separate ML techniques must become one approval judgement. The right answer may be to reject deployment until evidence is repaired. Being an architect means knowing which attractive score is not enough.",
        "safe_vs_unsafe": ["Unsafe: list validation, monitoring, and calibration without issuing a decision.", "Safe: connect evidence, risk, release condition, trigger, owner, and action."],
        "mini_checks": ["What would make you reject release?", "What evidence changes rejection to conditional approval?", "Who owns the first breach?"],
    },
    "capstone_ml_architect_001": {
        "teacher_walkthrough": "Treat the capstone as a compact architecture review pack. Each answer is an artifact section, not an essay. The centre of gravity is the decision: what gets deployed, under which restrictions, because of which evidence, and with which controls.",
        "safe_vs_unsafe": ["Unsafe: model-first build with accuracy and a vague dashboard.", "Safe: decision-first pipeline with measurable risk controls and release gates."],
        "mini_checks": ["What is the release recommendation?", "Which artifact supports it?", "Which failure would stop or roll back the model?"],
    },
}
