[theme]
base = "light"
primaryColor = "#205ECF"
backgroundColor = "#F6F8FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#172033"
font = "sans serif"

[server]
runOnSave = true

[client]
toolbarMode = "minimal"

[ui]
hideTopBar = true

[browser]
gatherUsageStats = false