[theme]
base = "light"
primaryColor = "#245A92"
backgroundColor = "#E6ECF3"
secondaryBackgroundColor = "#F2F5F9"
textColor = "#1D293B"
font = "sans serif"

[server]
runOnSave = true

[client]
toolbarMode = "minimal"

[ui]
hideTopBar = true

[browser]
gatherUsageStats = false
